version: '3.8'

networks:
  app-tier:
    driver: bridge

services: 
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-tier
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: node-mysql-app
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes: 
      - ./app:/app
    networks:
      - app-tier
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes: 
  db:
  db-config:
  db-data: